framework:
    rate_limiter:
        # Définir 2 rate limiters (un pour le couple nom d'utilisateur + IP, l'autre pour l'IP seule)
        username_ip_login:
            policy: token_bucket
            limit: 5
            rate:
                interval: '5 minutes'

        ip_login:
            policy: sliding_window
            limit: 50
            interval: '15 minutes'

services:
    # Notre rate limiter de connexion personnalisé
    app.login_rate_limiter:
        class: Symfony\Component\Security\Http\RateLimiter\DefaultLoginRateLimiter
        arguments:
            $globalFactory: '@limiter.ip_login'
            $localFactory: '@limiter.username_ip_login'
            $secret: '%kernel.secret%'

security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern:
                - ^/_profiler/
                - ^/_wdt/
                - ^/css/
                - ^/images/
                - ^/js/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            json_login:
                # api_login est une route que nous créerons ci-dessous
                check_path: api_login
            http_basic:
                realm: Secured Area
            logout:
                path: /logout
            x509:
                # configuration x509 si nécessaire
            remote_user:
                # configuration remote_user si nécessaire
            login_throttling: null

            # Configurer le nombre maximum de tentatives de connexion
            login_throttling:
                limiter: 'app.login_rate_limiter'

            # Activer différentes méthodes d'authentification
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_u
